# Generated by Django 5.0.7 on 2024-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('owner', 'Owner'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
