# Generated by Django 5.0.4 on 2024-06-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolspace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pool_space',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='app.poolspace'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
    ]
