# Generated by Django 5.0.4 on 2024-06-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_poolspace_status_alter_tournament_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='pool_space',
        ),
    ]
