# Generated by Django 5.0.4 on 2024-06-22 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mpesatransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='enrollment',
            field=models.ForeignKey(default='7c0cc402-c324-4daf-bf2f-2f229ab100ed', on_delete=django.db.models.deletion.CASCADE, to='app.enrollment'),
            preserve_default=False,
        ),
    ]
