# Generated by Django 5.0.4 on 2024-06-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mpesatransaction_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
