# Generated by Django 5.0.4 on 2024-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mpesatransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
