# Generated by Django 5.0.4 on 2024-07-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tournament_pool_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='pool_space',
        ),
    ]
