# Generated by Django 5.0.4 on 2024-07-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_poolspace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pool_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='app.poolspace'),
            preserve_default=False,
        ),
    ]
