# Generated by Django 5.0.4 on 2024-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tournament_pool_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolspace',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolspace',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
