# Generated by Django 5.0.4 on 2024-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_poolspace_latitude_alter_poolspace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolspace',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poolspace',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poolspace',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='poolspace',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
