# Generated by Django 5.0.4 on 2024-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_poolspace_height_alter_poolspace_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
