# Generated by Django 5.0.4 on 2024-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mpesatransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
